service: aws-python-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  environment:
    MONGODB_PASSWORD: ${ssm:/mongodb/password}

plugins:
  - serverless-python-requirements

package:
  exclude:
    - node_modules/**
    - __pycache__/**
    - .git/**
    - .gitignore
    - README.md
    - venv/**
    - package-lock

functions:
  createChat:
    handler: src/handler.crate_chat
    name: lambda-create-chat-first-conversation
    events:
      - httpApi:
          path: /
          method: post
  insertMessage:
    handler: src/handler.inset_message
    name: lambda-insert-message-into-chat
    events:
      - httpApi:
          path: /
          method: put